export const plans = [
  {
    id: "starter",
    name: "Starter",
    blurb: "Punch attendance. Chat from the CRM inbox — not from one person’s phone.",
    featured: false,
    price: "₹3,000",
    priceSuffix: "/ month",
    priceCaption: "Starting · one campus",
    includes: [
      "Student and staff attendance",
      "Attendance WhatsApp to parents (when you switch it on)",
      "Official WhatsApp inbox in the CRM",
      "Any staff login can open the same chat",
    ],
  },
  {
    id: "fees",
    name: "Starter + Fees",
    blurb: "Starter, plus collect fees and send the PDF receipt.",
    featured: false,
    price: "₹6,000",
    priceSuffix: "/ month",
    priceCaption: "One campus",
    includes: [
      "Everything in Starter",
      "Fee collection",
      "Fee receipt PDF — View PDF / Download PDF",
      "Late fees on your rule",
      "Fee reminder on WhatsApp",
    ],
  },
  {
    id: "full_crm",
    name: "Full CRM",
    blurb: "The full desk: leads, calling, admission, parent login, reports, results.",
    featured: true,
    price: "₹10,000",
    priceSuffix: "/ month",
    priceCaption: "One campus · all features",
    includes: [
      "Everything in Starter + Fees",
      "Leads, visits and calling",
      "Admission, roll number, batch",
      "Find student by mobile",
      "Parent / student portal",
      "Homework, exams, results, PDF marksheets",
      "Certificates",
      "Reports",
      "Institute website CMS",
    ],
  },
] as const;
