export const site = {
  name: "Task Book",
  tagline: "Manage. Automate. Connect.",
  pitch:
    "Attendance and fee reminders on WhatsApp. Team chats from the CRM, not from one person’s phone. Type a mobile number and the full file opens.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://taskbook.co.in",
  whatsappNumber: (process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? "91XXXXXXXXXX").replace(
    /\D/g,
    "",
  ),
  email: "hello@taskbook.co.in",
} as const;

export function whatsappHref(message?: string) {
  const text =
    message ??
    "Hi, I run a school/college/institute and want a Task Book demo.";
  return `https://wa.me/${site.whatsappNumber}?text=${encodeURIComponent(text)}`;
}

export const nav = [
  { href: "/features", label: "Features" },
  {
    href: "/schools",
    label: "Solutions",
    children: [
      { href: "/schools", label: "Schools" },
      { href: "/colleges", label: "Colleges" },
      { href: "/institutes", label: "Institutes" },
    ],
  },
  { href: "/pricing", label: "Pricing" },
  { href: "/blog", label: "Blog" },
] as const;

export const hero = {
  headline: "WhatsApp to parents. Chat from the CRM. Type a number, see the full file.",
  subhead:
    "Task Book is for school, college and institute owners. Attendance and fee reminders go on your official WhatsApp. Staff log in and talk from the software — same Meta-approved number, chat history stays even if one person is on leave.",
};

export const pains = [
  {
    n: "01",
    title: "The chat lives on one person’s phone",
    body: "That counsellor is on leave, or they leave the job. Nobody else can see what the parent said. The next person starts from zero.",
  },
  {
    n: "02",
    title: "Parents call for things the school already knows",
    body: "Did the child reach? Why is fee pending? The office answers this by hand, every day.",
  },
  {
    n: "03",
    title: "A visitor comes back and nobody remembers",
    body: "How many times they came, whom they met, what was said, how many times you called — it is in a diary, or in someone’s head.",
  },
] as const;

export const howItWorks = [
  {
    step: "1",
    title: "Someone walks in, or they call",
    body: "Staff types the registered mobile number. That is the starting point — not a new form every time.",
  },
  {
    step: "2",
    title: "If they are a visitor or a lead",
    body: "You see how many times they came, whom they met, what they asked, and how many times your team called them.",
  },
  {
    step: "3",
    title: "Team talks on call and on WhatsApp",
    body: "Calling is from the CRM. WhatsApp is also inside the CRM. Any staff login can open the same chat. History does not sit on one phone.",
  },
  {
    step: "4",
    title: "When they take admission",
    body: "They become a student. Unique roll number. Batch assigned. The old visit and call history stays on the same person.",
  },
  {
    step: "5",
    title: "After they join, parents stop calling for the small things",
    body: "The child punches in — parent gets WhatsApp. Fee is pending — parent gets a reminder. Same institute number. The front desk is free for real work.",
  },
  {
    step: "6",
    title: "You collect the fee. The PDF is already there.",
    body: "The receipt is generated by the software — institute name, receipt number, amount in words. Staff tap View PDF or Download PDF. When you want a list, you download a report. No Excel on Saturday.",
  },
] as const;

export const moduleShots: Record<string, string> = {
  "whatsapp-inbox": "/screens/crm-inbox.png",
  "whatsapp-attendance": "/screens/phone-attendance.png",
  "student-360": "/screens/find-student.png",
  leads: "/screens/visitor-file.png",
  admissions: "/screens/student-file.png",
  fees: "/screens/fee-slip.png",
  portal: "/screens/student-file.png",
  exams: "/screens/reports-dash.png",
  homework: "/screens/phone-fee.png",
  reports: "/screens/reports-dash.png",
  staff: "/screens/crm-inbox.png",
};

export const clients = [
  { name: "Motion Education", host: "motion.taskbook.co.in", logo: "/logos/motion-logo.svg" },
  { name: "Horizon", host: "horizon.taskbook.co.in", logo: "/logos/horizon-logo.svg" },
] as const;
